### ISSUE TITLE
`style` attribut in package.json

### ISSUE THREAD

**Issue by dtothefp** [suitcss/theme#4]
I read in `webpack-postcss-tools` [repo](https://github.com/aaronj1335/webpack-postcss-tools/blob/master/examples/one-link-element/webpack.config.js#L11) `webpack.config.js` about a `style` attribute in `package.json` SUIT projects. I saw this in your project `"style": "theme.css"` and I'm wondering what it does?

**Comment by simonsmith** [comment]
I believe this is the equivalent of the `main` property so that when you require the package the tool in question (used to be `rework-npm`) knows what file to import. Basically you can just give webpack a list of properties to look at for getting a reference to the CSS file.

Most SUIT packages make use of an [`index.js`](https://github.com/suitcss/components-grid/blob/master/index.js) to achieve this now.
